name: "nllb-600M_ensemble"
platform: "ensemble"
max_batch_size: 8
input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "TEXT_OUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "nllb-600M_tokenize"
      model_version: 1
      input_map {
        key: "TEXT"
        value: "TEXT"
      }
      output_map {
        key: "input_ids"
        value: "input_ids"
      }
    },
    {
      model_name: "nllb-600M_translation"
      model_version: 1
      input_map {
        key: "input_ids"
        value: "input_ids"
      }

      output_map {
        key: "output_ids"
        value: "output_ids"
      }
    },
    {
      model_name: "nllb-600M_detokenize"
      model_version: 1
      input_map {
        key: "output_ids"
        value: "output_ids"
      }
      output_map {
        key: "TEXT"
        value: "TEXT_OUT"
      }
    }
  ]
}